CREATE TABLE IF NOT EXISTS campaigns_images (
    id INT PRIMARY KEY AUTO_INCREMENT,
    campaign_id INT,
    file_name VARCHAR(255),
    is_primary TINYINT(1) DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE
);